language: python
dist: xenial

python:
  - "2.7"

sudo: required

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

#addons:
#  apt:
#    packages:
#      - expect-dev  # provides unbuffer utility
#      - python-lxml  # because pip installation is slow
#      - libappindicator1
#      - fonts-liberation
#      - chromium-browser
#      - chromium-chromedriver

env:
#  - VERSION="10.0" DOC="0" ROBOT="0"
#  - VERSION="10.0" DOC="1" ROBOT="0"
#  - VERSION="10.0" DOC="0" ROBOT="1"
#  - VERSION="10.0" ODOO_REPO="odoo/odoo"
  - VERSION="10.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 5
#  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
#  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
#  - ./travis_install_buildout
  - sudo locale-gen en_US en_US.UTF-8 pt_BR.UTF-8
  - sudo dpkg-reconfigure locales
  - provision/bootstrap-packages-ubuntu-xenial.sh
  - provision/bootstrap-database.sh
  - provision/bootstrap-environment.sh

install:
  - bin/buildout -N -t 20

script:
  - provision/travis_run_script

after_success:
  - bash <(curl -s https://codecov.io/bash)

#after_success:
#  - bin/start_openerp &
#  - bin/pybot -v CONFIG:config_80.py robot/sale_stock_invoice_workflow.robot
#  - bin/travis-sphinx deploy
